apiVersion: v1
kind: Service
metadata:
  name: aukro-service
  namespace: statex-apps
  labels:
    app: aukro-service
    managed-by: k8s-migration
spec:
  type: ClusterIP
  selector:
    app: aukro-service
  ports:
    - protocol: TCP
      port: 3700
      targetPort: 3700
      name: app
